# Assignment No 1 : Data wrangling 1

---

## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

## 2. Locate open source data from web

**Dataset link :** https://www.kaggle.com/c/titanic/data

## 3. Load the dataset into Pandas Dataframe

In [2]:
df = pd.read_csv("Data Set/train (1).csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 4. Data Preprocessing

In [3]:
# check dimensions of dataframe
df.shape

(891, 12)

In [4]:
# check the columns present
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
# check total size (rows * columns)
df.size

10692

In [6]:
# check datatypes of each column
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [7]:
#check for missing values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
# check initial statistics
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
# Print information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 5. Data Formatting and Data Normalization

In [10]:
# Handling missing values
# 1. fillna() : method which we can use replace null(NaN) values with some other value
# or we can perform forward fill(ffill), backward fill(bfill).

# 2. interpolate() : performs linear interpolation(by default but you can change)
# and replaces the null with the result.

# 3. dropna() : It will drop all the rows that have NaN values. but using this
# method we lose data.

df["Cabin"] = df["Cabin"].replace(to_replace=np.nan, value="unknown")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,unknown,Q

In [11]:
df["Age"] = df["Age"].interpolate()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,22.5,1,2,W./C. 6607,23.4500,unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,unknown,Q

In [12]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

In [13]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,22.5,1,2,W./C. 6607,23.4500,unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,unknown,Q

In [14]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [15]:
# Changing Datatypes
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [16]:
df["Age"] = df["Age"].astype('int64')
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## 6. Turning categorical variables into quantitive

In [17]:
quantitative_data = pd.get_dummies(df.Embarked, prefix='Embarked')
quantitative_data

     Embarked_C  Embarked_Q  Embarked_S
0         False       False        True
1          True       False       False
2         False       False        True
3         False       False        True
4         False       False        True
..          ...         ...         ...
886       False       False        True
887       False       False        True
888       False       False        True
889        True       False       False
890       False        True       False

[891 rows x 3 columns]

In [18]:
df = df.join(quantitative_data)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,unknown,S,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,unknown,S,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,unknown,S,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,unknown,S,False,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S,False,False,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,22,1,2,W./C. 6607,23.4500,unknown,S,False,False,True
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C,True,False,False
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,unknown,Q,False,True,False

In [19]:
df.drop(['Embarked'], axis=1, inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,unknown,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,unknown,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,unknown,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,unknown,False,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,False,False,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,22,1,2,W./C. 6607,23.4500,unknown,False,False,True
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,True,False,False
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,unknown,False,True,False

In [21]:
# =============================================================================
# IMPORTANT NOTES FOR ORAL EXAM - DATA WRANGLING I
# =============================================================================

# --------------------------------------------------------------------------
# WHAT IS DATA WRANGLING?
# --------------------------------------------------------------------------
# Data Wrangling (also called Data Munging) is the process of cleaning,
# transforming, and organizing raw data into a usable format for analysis.
# Raw data is often messy - it has missing values, wrong data types,
# inconsistent formats, etc. Data wrangling fixes all these issues.

# --------------------------------------------------------------------------
# DATASET USED - TITANIC DATASET
# --------------------------------------------------------------------------
# Source  : Kaggle (https://www.kaggle.com/c/titanic/data)
# About   : This dataset contains information about passengers on the Titanic
#           ship - like their age, gender, ticket class, fare, cabin, and
#           whether they survived or not.
# Columns : PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch,
#           Ticket, Fare, Cabin, Embarked

# --------------------------------------------------------------------------
# LIBRARIES USED
# --------------------------------------------------------------------------
# pandas (pd) : Used for data manipulation and analysis.
#               It provides the DataFrame structure to store and work with data.
# numpy  (np) : Used for numerical operations.
#               Here we use np.nan which represents a missing/null value.

# --------------------------------------------------------------------------
# STEP 1 - LOADING DATA
# --------------------------------------------------------------------------
# pd.read_csv() : Reads a CSV file and loads it into a Pandas DataFrame.
# A DataFrame is like a table (rows and columns), similar to an Excel sheet.
# df is the variable name we give to our loaded dataset.

# --------------------------------------------------------------------------
# STEP 2 - DATA PREPROCESSING (Exploring the Data)
# --------------------------------------------------------------------------
# Before cleaning data, we first explore it to understand its structure.

# df.shape   : Returns (rows, columns) - tells us how big the dataset is.
#              Example output: (891, 12) means 891 rows and 12 columns.

# df.columns : Shows the names of all columns in the dataset.

# df.size    : Returns total number of elements = rows * columns.
#              Example: 891 * 12 = 10692

# df.dtypes  : Shows the data type of each column.
#              Common types: int64 (integers), float64 (decimals),
#              object (text/string), bool (True/False).

# df.isnull().sum() : Checks for missing values in each column.
#              isnull() returns True where value is missing (NaN).
#              .sum() counts how many True values (missing values) per column.
#              In Titanic: Age, Cabin, Embarked columns have missing values.

# df.describe() : Shows basic statistics for numerical columns.
#              Includes: count, mean, std (standard deviation),
#              min, 25%, 50% (median), 75%, max.
#              Helps understand the distribution of data.

# df.info()  : Prints a summary of the DataFrame.
#              Shows column names, non-null count, and data types.
#              Useful to quickly spot columns with missing values.

# --------------------------------------------------------------------------
# STEP 3 - HANDLING MISSING VALUES (Most Important Part)
# --------------------------------------------------------------------------
# Missing values are represented as NaN (Not a Number) in pandas.
# We cannot use data with missing values directly in ML models, so we fix them.

# There are 3 main methods to handle missing values:

# METHOD 1 - replace() / fillna() with a fixed value:
#   df["Cabin"].replace(to_replace=np.nan, value="unknown")
#   - Cabin column had many missing values.
#   - We replaced all NaN values with the string "unknown".
#   - This is useful when we don't want to lose rows but the data is missing.

# METHOD 2 - interpolate():
#   df["Age"].interpolate()
#   - Age column had some missing values.
#   - interpolate() fills missing values by calculating the average
#     between the previous and next value (linear interpolation).
#   - Example: if values are 20, NaN, 30 -> it fills NaN with 25.
#   - Best used for numerical columns where values follow a pattern.

# METHOD 3 - fillna() with mode:
#   df['Embarked'].fillna(df['Embarked'].mode()[0])
#   - Embarked column had 2 missing values.
#   - mode() gives the most frequently occurring value.
#   - [0] is used because mode() returns a Series, we take the first value.
#   - We fill missing values with the most common port of embarkation.
#   - Best used for categorical (text) columns.

# METHOD 4 - dropna() (mentioned but not used here):
#   df.dropna()
#   - Drops all rows that contain any NaN value.
#   - Simple but causes data loss, so we avoid it when possible.

# --------------------------------------------------------------------------
# STEP 4 - CHANGING DATA TYPES
# --------------------------------------------------------------------------
# df["Age"].astype('int64')
# - After interpolation, Age column becomes float (decimal) type.
# - Age should be a whole number (integer), so we convert it to int64.
# - astype() is used to change the data type of a column.
# - Common types: 'int64', 'float64', 'str', 'bool'

# --------------------------------------------------------------------------
# STEP 5 - TURNING CATEGORICAL VARIABLES INTO QUANTITATIVE (One-Hot Encoding)
# --------------------------------------------------------------------------
# Machine Learning models only understand numbers, not text.
# The 'Embarked' column has text values: 'S', 'C', 'Q'
# (S = Southampton, C = Cherbourg, Q = Queenstown)
# We need to convert these text categories into numbers.

# pd.get_dummies(df.Embarked, prefix='Embarked')
# - This is called ONE-HOT ENCODING.
# - It creates a new binary (0 or 1) column for each unique category.
# - For 'Embarked' with values S, C, Q -> it creates 3 new columns:
#   Embarked_C, Embarked_Q, Embarked_S
# - If a passenger embarked from 'S', then Embarked_S = 1, others = 0.
# - prefix='Embarked' adds 'Embarked_' before each new column name.

# df.join(quantitative_data)
# - Adds the new dummy columns to the original dataframe.

# df.drop(['Embarked'], axis=1, inplace=True)
# - After creating dummy columns, we remove the original 'Embarked' column
#   because it is no longer needed.
# - axis=1 means we are dropping a column (axis=0 would drop a row).
# - inplace=True means the change is applied directly to df (no need to reassign).

# --------------------------------------------------------------------------
# KEY TERMS TO REMEMBER
# --------------------------------------------------------------------------
# NaN          : Not a Number - represents a missing value in pandas/numpy.
# DataFrame    : A 2D table structure with rows and columns (like Excel sheet).
# Interpolation: Estimating missing values based on surrounding known values.
# Mode         : The value that appears most frequently in a column.
# One-Hot Encoding : Converting text categories into binary (0/1) columns.
# dtype        : Data type of a column (int, float, object, bool).
# inplace=True : Modifies the original DataFrame directly without reassigning.
# axis=1       : Refers to columns; axis=0 refers to rows.

# --------------------------------------------------------------------------
# POSSIBLE ORAL EXAM QUESTIONS & ANSWERS
# --------------------------------------------------------------------------
# Q: What is Data Wrangling?
# A: Data Wrangling is the process of cleaning and transforming raw, messy data
#    into a clean and usable format for analysis or machine learning.

# Q: What dataset is used and where is it from?
# A: Titanic dataset from Kaggle. It has passenger info like age, sex, class,
#    cabin, and whether they survived.

# Q: How do you check missing values?
# A: Using df.isnull().sum() - it shows the count of missing values per column.

# Q: What is the difference between fillna() and interpolate()?
# A: fillna() replaces missing values with a fixed value (like mode or mean).
#    interpolate() calculates the missing value mathematically based on
#    neighboring values (linear by default).

# Q: Why do we use get_dummies()?
# A: To convert categorical (text) columns into numerical format using
#    one-hot encoding, because ML models only work with numbers.

# Q: Why do we drop the original 'Embarked' column after get_dummies()?
# A: Because the information is already captured in the new dummy columns
#    (Embarked_C, Embarked_Q, Embarked_S). Keeping the original would be
#    redundant.

# Q: What does astype() do?
# A: It converts the data type of a column. For example, converting float to
#    int after interpolation fills decimal values in the Age column.

# Q: What is the difference between df.shape and df.size?
# A: df.shape gives (rows, columns) as a tuple.
#    df.size gives total elements = rows * columns as a single number.
# =============================================================================