# Assignment No 3 : Descriptive Statistics - Measures of Central Tendency and Variability

---

## Import Required Libraries

In [147]:
import pandas as pd
import numpy as np

## Read csv into Dataframe

In [148]:
df = pd.read_csv('Data Set/iris.csv')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## # Data Preprocessing

In [149]:
df.shape

(150, 5)

In [150]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [151]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [153]:
# Rename columns to standard names
df.columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
0              5.1           3.5            1.4           0.2     setosa
1              4.9           3.0            1.4           0.2     setosa
2              4.7           3.2            1.3           0.2     setosa
3              4.6           3.1            1.5           0.2     setosa
4              5.0           3.6            1.4           0.2     setosa
..             ...           ...            ...           ...        ...
145            6.7           3.0            5.2           2.3  virginica
146            6.3           2.5            5.0           1.9  virginica
147            6.5           3.0            5.2           2.0  virginica
148            6.2           3.4            5.4           2.3  virginica
149            5.9           3.0            5.1           1.8  virginica

[150 rows x 5 columns]

In [154]:
# Drop Id column if present, else skip
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0            5.1           3.5            1.4           0.2  setosa
1            4.9           3.0            1.4           0.2  setosa
2            4.7           3.2            1.3           0.2  setosa
3            4.6           3.1            1.5           0.2  setosa
4            5.0           3.6            1.4           0.2  setosa

## # Calculating mean

In [155]:
df.mean(numeric_only=True)

SepalLengthCm    5.843333
SepalWidthCm     3.054000
PetalLengthCm    3.758667
PetalWidthCm     1.198667
dtype: float64

## # Calculating median

In [156]:
df.median(numeric_only=True)

SepalLengthCm    5.80
SepalWidthCm     3.00
PetalLengthCm    4.35
PetalWidthCm     1.30
dtype: float64

## # Calculating mode

In [157]:
df.mode()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
0            5.0           3.0            1.5           0.2      setosa
1            NaN           NaN            NaN           NaN  versicolor
2            NaN           NaN            NaN           NaN   virginica

## # Calculating standard deviation

In [158]:
df.std(numeric_only=True)

SepalLengthCm    0.828066
SepalWidthCm     0.433594
PetalLengthCm    1.764420
PetalWidthCm     0.763161
dtype: float64

## # Calculating variance

In [159]:
df.var(numeric_only=True)

SepalLengthCm    0.685694
SepalWidthCm     0.188004
PetalLengthCm    3.113179
PetalWidthCm     0.582414
dtype: float64

## # Calculating minimum value

In [160]:
np.min(df.select_dtypes(include='number'))

0.1

## # Calculating maximum value

In [161]:
np.max(df.select_dtypes(include='number'))

7.9

## # Calculating 1st quantile (25th percentile)

In [162]:
df.quantile(0.25, numeric_only=True)

SepalLengthCm    5.1
SepalWidthCm     2.8
PetalLengthCm    1.6
PetalWidthCm     0.3
Name: 0.25, dtype: float64

## # Calculating 2nd quantile (50th percentile)

In [163]:
df.quantile(0.50, numeric_only=True)

SepalLengthCm    5.80
SepalWidthCm     3.00
PetalLengthCm    4.35
PetalWidthCm     1.30
Name: 0.5, dtype: float64

## # Calculating 3rd quantile (75th percentile)

In [164]:
df.quantile(0.75, numeric_only=True)

SepalLengthCm    6.4
SepalWidthCm     3.3
PetalLengthCm    5.1
PetalWidthCm     1.8
Name: 0.75, dtype: float64

In [ ]:
# =============================================================================
# IMPORTANT NOTES FOR ORAL EXAM
# DESCRIPTIVE STATISTICS - MEASURES OF CENTRAL TENDENCY AND VARIABILITY
# =============================================================================

# --------------------------------------------------------------------------
# WHAT IS DESCRIPTIVE STATISTICS?
# --------------------------------------------------------------------------
# Descriptive Statistics is a branch of statistics that summarizes and
# describes the main features of a dataset.
# It does NOT make predictions - it just describes what the data looks like.
# It is divided into two main parts:
#   1. Measures of Central Tendency  -> Where is the center of the data?
#   2. Measures of Variability       -> How spread out is the data?

# --------------------------------------------------------------------------
# DATASET USED - IRIS DATASET
# --------------------------------------------------------------------------
# The Iris dataset is one of the most famous datasets in data science.
# It contains measurements of 150 iris flowers from 3 different species:
#   - Iris Setosa
#   - Iris Versicolor
#   - Iris Virginica
#
# Columns (after renaming):
#   - SepalLengthCm : Length of the sepal in centimeters
#   - SepalWidthCm  : Width of the sepal in centimeters
#   - PetalLengthCm : Length of the petal in centimeters
#   - PetalWidthCm  : Width of the petal in centimeters
#   - Species       : Type of iris flower (categorical)
#
# Shape: 150 rows x 5 columns
# No missing values in this dataset.

# --------------------------------------------------------------------------
# LIBRARIES USED
# --------------------------------------------------------------------------
# pandas (pd) : For loading and analyzing data using DataFrames.
# numpy  (np) : For numerical operations like min and max.

# --------------------------------------------------------------------------
# DATA PREPROCESSING
# --------------------------------------------------------------------------
# df.shape          : Returns (150, 5) - 150 rows and 5 columns.
# df.isnull().sum() : Checks for missing values - all zeros (no missing data).
# df.dtypes         : Shows data types - 4 float columns + 1 object (Species).
# df.info()         : Summary of DataFrame - column names, types, non-null count.
# df.columns = [...]: Renames columns to standard readable names.
# df.head()         : Shows first 5 rows to verify the data looks correct.

# --------------------------------------------------------------------------
# MEASURES OF CENTRAL TENDENCY
# (These tell us where the CENTER or MIDDLE of the data is)
# --------------------------------------------------------------------------

# 1. MEAN (Average)
#    df.mean(numeric_only=True)
#    - Adds all values and divides by the count.
#    - Formula: Mean = Sum of all values / Number of values
#    - Example: Mean of [2, 4, 6] = (2+4+6)/3 = 4
#    - numeric_only=True : Only calculates for numerical columns (ignores Species).
#    - Sensitive to outliers (extreme values can pull the mean up or down).

# 2. MEDIAN (Middle Value)
#    df.median(numeric_only=True)
#    - The middle value when data is sorted in order.
#    - If even number of values, median = average of two middle values.
#    - Example: Median of [1, 3, 5, 7, 9] = 5
#    - NOT sensitive to outliers (better than mean for skewed data).

# 3. MODE (Most Frequent Value)
#    df.mode()
#    - The value that appears most often in the data.
#    - Example: Mode of [1, 2, 2, 3, 4] = 2
#    - A dataset can have more than one mode (bimodal, multimodal).
#    - Useful for both numerical and categorical data.
#    - Note: df.mode() works on all columns including Species.

# --------------------------------------------------------------------------
# MEASURES OF VARIABILITY / DISPERSION
# (These tell us how SPREAD OUT the data is)
# --------------------------------------------------------------------------

# 4. STANDARD DEVIATION
#    df.std(numeric_only=True)
#    - Measures how much values deviate (differ) from the mean on average.
#    - Low std  -> values are close to the mean (less spread).
#    - High std -> values are far from the mean (more spread).
#    - Formula: std = sqrt(variance)
#    - Same unit as the original data (e.g., cm).

# 5. VARIANCE
#    df.var(numeric_only=True)
#    - Average of the squared differences from the mean.
#    - Formula: variance = sum((x - mean)^2) / (n - 1)  [sample variance]
#    - Higher variance = more spread out data.
#    - Unit is squared (e.g., cm^2), so std is preferred for interpretation.
#    - Relationship: variance = std^2

# 6. MINIMUM VALUE
#    np.min(df.select_dtypes(include='number'))
#    - Returns the smallest value in each numerical column.
#    - select_dtypes(include='number') selects only numerical columns.
#    - np.min() then finds the minimum of each selected column.

# 7. MAXIMUM VALUE
#    np.max(df.select_dtypes(include='number'))
#    - Returns the largest value in each numerical column.
#    - Same approach as minimum but finds the highest value.

# --------------------------------------------------------------------------
# QUANTILES / PERCENTILES
# (These divide the data into equal parts)
# --------------------------------------------------------------------------

# 8. 1st QUARTILE - Q1 (25th Percentile)
#    df.quantile(0.25, numeric_only=True)
#    - 25% of the data falls BELOW this value.
#    - Also called the lower quartile.

# 9. 2nd QUARTILE - Q2 (50th Percentile)
#    df.quantile(0.50, numeric_only=True)
#    - 50% of the data falls BELOW this value.
#    - This is the same as the MEDIAN.

# 10. 3rd QUARTILE - Q3 (75th Percentile)
#     df.quantile(0.75, numeric_only=True)
#     - 75% of the data falls BELOW this value.
#     - Also called the upper quartile.

# INTERQUARTILE RANGE (IQR) - Important concept:
#     IQR = Q3 - Q1
#     - Measures the spread of the middle 50% of data.
#     - Used to detect outliers:
#       Values below Q1 - 1.5*IQR or above Q3 + 1.5*IQR are outliers.

# --------------------------------------------------------------------------
# SUMMARY TABLE - ALL MEASURES AT A GLANCE
# --------------------------------------------------------------------------
# | Measure            | Function                        | What it tells us         |
# |--------------------|----------------------------------|---------------------------|
# | Mean               | df.mean(numeric_only=True)       | Average value             |
# | Median             | df.median(numeric_only=True)     | Middle value              |
# | Mode               | df.mode()                        | Most frequent value       |
# | Std Deviation      | df.std(numeric_only=True)        | Spread around mean        |
# | Variance           | df.var(numeric_only=True)        | Squared spread            |
# | Minimum            | np.min(df.select_dtypes(...))    | Smallest value            |
# | Maximum            | np.max(df.select_dtypes(...))    | Largest value             |
# | Q1 (25%)           | df.quantile(0.25)                | Lower quartile            |
# | Q2 (50%) = Median  | df.quantile(0.50)                | Middle quartile           |
# | Q3 (75%)           | df.quantile(0.75)                | Upper quartile            |

# --------------------------------------------------------------------------
# KEY TERMS TO REMEMBER
# --------------------------------------------------------------------------
# Central Tendency  : A single value that represents the center of the data.
# Variability       : How spread out or scattered the data values are.
# Outlier           : A value that is very different from the rest of the data.
# Percentile        : Value below which a given % of data falls.
# Quartile          : Divides data into 4 equal parts (Q1, Q2, Q3).
# IQR               : Interquartile Range = Q3 - Q1 (middle 50% spread).
# numeric_only=True : Tells pandas to only calculate for number columns.
# select_dtypes()   : Selects columns of a specific data type.

# --------------------------------------------------------------------------
# POSSIBLE ORAL EXAM QUESTIONS & ANSWERS
# --------------------------------------------------------------------------
# Q: What is Descriptive Statistics?
# A: It is a branch of statistics that summarizes and describes the main
#    features of a dataset using measures like mean, median, mode,
#    standard deviation, etc. It does not make predictions.

# Q: What dataset is used and what does it contain?
# A: The Iris dataset with 150 rows and 5 columns - SepalLengthCm,
#    SepalWidthCm, PetalLengthCm, PetalWidthCm, and Species (3 flower types).

# Q: What is the difference between Mean, Median, and Mode?
# A: Mean = average of all values.
#    Median = middle value when sorted.
#    Mode = most frequently occurring value.

# Q: When should we use Median instead of Mean?
# A: When the data has outliers or is skewed. Median is not affected by
#    extreme values, so it gives a better picture of the center.

# Q: What is the difference between Variance and Standard Deviation?
# A: Variance is the average of squared differences from the mean.
#    Standard Deviation is the square root of variance.
#    Std is preferred because it has the same unit as the original data.

# Q: What are Quartiles?
# A: Quartiles divide data into 4 equal parts.
#    Q1 = 25th percentile (lower quartile)
#    Q2 = 50th percentile (median)
#    Q3 = 75th percentile (upper quartile)

# Q: What is IQR and how is it used?
# A: IQR = Q3 - Q1. It measures the spread of the middle 50% of data.
#    It is used to detect outliers:
#    Values below Q1 - 1.5*IQR or above Q3 + 1.5*IQR are considered outliers.

# Q: What does numeric_only=True do?
# A: It tells pandas to only calculate statistics for numerical columns
#    and ignore text/categorical columns like Species.

# Q: What does select_dtypes(include='number') do?
# A: It selects only the columns that have numerical data types (int or float),
#    ignoring string/object columns. Used before np.min() and np.max().
# =============================================================================